version: '3'

services:
    php:
        build: ./docker/php-fpm
        volumes:
            - ./:/srv/walletaccountantcommander:delegated
        depends_on:
            - mongo
            - mariadb
        links:
          - mariadb
        networks:
           - commander
    nginx:
        image: 'nginx:1.13-alpine'
        ports:
            - '9000:80'
        depends_on:
            - php
        volumes:
            - './docker/nginx/conf.d:/etc/nginx/conf.d:ro'
            - ./var/nginx/logs/:/var/log/nginx:delegated
            - ./:/srv/walletaccountantcommander:delegated
        networks:
           - commander
    mongo:
        image: 'mongo:3.6-jessie'
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
            - MONGODB_USER="user"
            - MONGODB_PASS="password"
        volumes:
            - ./data/mongo:/data/db:delegated
        ports:
            - 27017:27017
        networks:
            - commander
    mariadb:
        image: 'mariadb:10.3.2'
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_USER = evtstr
            - MYSQL_PASSWORD = mynormalpw
            - MYSQL_DATABASE = events
        ports:
            - 3306:3306
        networks:
            - commander

networks:
    commander:
