version: '2.1'

services:
    php:
        build: ./docker/php-fpm
        volumes:
            - ./:/srv/walletaccountantcommander
    nginx:
        image: 'nginx:1.13-alpine'
        depends_on:
            php:
                condition: 'service_started'
        ports:
            - '9000:80'
        volumes_from:
            - php
        volumes:
            - './docker/nginx/conf.d:/etc/nginx/conf.d:ro'
            - ./var/nginx/logs/:/var/log/nginx
