version: '3.4'

services:
    php:
        build: ./docker/php-fpm
        volumes:
            - ./:/srv/walletaccountantcommander:delegated
        depends_on:
            - mongo
            - mariadb
        links:
          - mariadb
        networks:
           - commander
    nginx:
        image: nginx:1.16-alpine
        ports:
            - 9000:80
        depends_on:
            - php
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./var/nginx/logs/:/var/log/nginx:delegated
            - ./:/srv/walletaccountantcommander:delegated
        networks:
           - commander
    mongo:
        image: mongo:4.1-bionic
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
            - MONGODB_USER="user"
            - MONGODB_PASS="password"
        volumes:
            - mongo-data:/data/db:delegated
        ports:
            - 27017:27017
        networks:
            - commander
    mariadb:
        image: mariadb:10.4
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_USER = evtstr
            - MYSQL_PASSWORD = mynormalpw
            - MYSQL_DATABASE = event_streams
        ports:
            - 3306:3306
        networks:
            - commander

networks:
    commander:

volumes:
    mongo-data:
