#index:
#    path: /
#    defaults: { _controller: 'WalletAccountant\Controller\DefaultController::index' }

test:
  path: /test
  defaults: { _controller: 'WalletAccountant\Controller\TestController::test' }

ping:
  path: /ping
  defaults: { _controller: 'WalletAccountant\Controller\PingController::ping' }

ping_authenticated:
  path: /ping-authenticated
  defaults: { _controller: 'WalletAccountant\Controller\PingController::pingAuthenticated' }

user_initiate_password_recovery:
  path: /initiate-password-recovery
  methods: [POST]
  defaults: { _controller: 'WalletAccountant\Controller\UserController::initiatePasswordRecovery' }

user_recover_password:
  path: /recover-password/{code}
  methods: [POST]
  defaults: { _controller: 'WalletAccountant\Controller\UserController::recoverPassword' }

user_update_name:
  path: /users/{id}/name
  methods: [PUT]
  defaults: { _controller: 'WalletAccountant\Controller\UserController::changeName' }

user_login:
  path: /login
  methods: [POST]
  defaults: { _controller: 'WalletAccountant\Controller\SecurityController::login' }

bank_create:
  path: /bank
  methods: [POST]
  defaults: { _controller: 'WalletAccountant\Controller\BankController::createBank' }

bank_update:
  path: /bank/{id}
  methods: [PUT]
  defaults: { _controller: 'WalletAccountant\Controller\BankController::updateBank' }
