#index:
#    path: /
#    defaults: { _controller: 'WalletAccountant\Controller\DefaultController::index' }

test:
    path: /test
    defaults: { _controller: 'WalletAccountant\Controller\TestController::test' }
