CREATE DATABASE IF NOT EXISTS events CHARACTER SET utf8 COLLATE utf8_bin;
CREATE USER IF NOT EXISTS 'evtstr'@'%' IDENTIFIED BY 'mynormalpw';
CREATE USER IF NOT EXISTS 'evtstr'@'localhost' IDENTIFIED BY 'mynormalpw';
GRANT ALL PRIVILEGES ON events.* TO 'evtstr'@'%';
FLUSH PRIVILEGES;
